---
title: "Biostatistics Course"
author: "Eleni-Rosalina Andrinopoulou, Department of Epidemiology and Department of Biostatistics, Erasmus Medical Center"
date: "`r Sys.setenv(LANG = 'en_US.UTF-8'); format(Sys.Date(), '%d %B %Y')`"
output: 
   html_document:
     toc: true
     toc_float:
       collapsed: false
     includes:
         after_body: footerEA.html
---
<style>
  .list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
    background-color: #4d4d4d;
  }
</style>

In this webpage, you can find the material of the Biostatistics I and II (NIHES CK020 and CK030) courses. In particular, these consist of the Introduction to R and Statistical tests part.


<div style="border:1px; border-style:solid; padding: 1em; border-color: #ffffff;
background: rgba(109, 121, 172, 0.4); color:black ">

# Introduction to R  
 
### _Slides_
 
- [Introduction](Slides\Biostatistics I\Introduction.pdf)

- [Basics](Slides\Biostatistics I\Basics.pdf)

- [Common_Objects](Slides\Biostatistics I\Common_Objects.pdf)

- [Indexing_Subsetting](Slides\Biostatistics I\Indexing_Subsetting.pdf)

- [Data Transformation Exploration Visualization](Slides\Biostatistics I\Data_Transformation_Exploration_Visualization.pdf)

- [Data Transformation Exploration Visualization](Slides\Biostatistics I\Data_Transformation_Exploration_Visualization.pdf)

- [Correlation](Slides\Biostatistics I\Correlation.pdf)
 
- [The Apply Family](Slides\Biostatistics II\The_Apply_Family.pdf)

### _Demos_

#### _Code_

- [Basics](Demos\Biostatistics I\01_Basics.R)

- [Importing Saving](Demos\Biostatistics I\02_Importing_Saving.R)

- [Common Objects](Demos\Biostatistics I\03_Common_Objects.R)

- [Indexing Subsetting](Demos\Biostatistics I\04_Indexing_Subsetting.R)

- [Data Transformation](Demos\Biostatistics I\05_Data_Transformation.R)

- [Data Exploration](Demos\Biostatistics I\06_Data_Exploration.R)

- [Data Visualization](Demos\Biostatistics I\07_Data_Visualization.R)

- [Distribution Functions](Demos\Biostatistics I\08_Distribution_Functions.R)

- [The Apply Family](Demos\Biostatistics II\The_Apply_Family.R)

- [Extra Programming Examples](Demos\Biostatistics II\Extra_Programming_Examples.R)


#### _Output_

- [Basics](Demos\Biostatistics I\01_Basics.html)

- [Importing Saving](Demos\Biostatistics I\02_Importing_Saving.html)

- [Common Objects](Demos\Biostatistics I\03_Common_Objects.html)

- [Indexing Subsetting](Demos\Biostatistics I\04_Indexing_Subsetting.html)

- [Data Transformation](Demos\Biostatistics I\05_Data_Transformation.html)

- [Data Exploration](Demos\Biostatistics I\06_Data_Exploration.html)

- [Data Visualization](Demos\Biostatistics I\07_Data_Visualization.html)

- [Distribution Functions](Demos\Biostatistics I\08_Distribution_Functions.html)

- [The Apply Family](Demos\Biostatistics II\The_Apply_Family.html)

- [Extra Programming Examples](Demos\Biostatistics II\Extra_Programming_Examples.html)


### _Practicals_

- [Importing Saving](Practicals\Biostatistics I\Introduction to R\01_Importing_Saving.html)

- [Common Objects](Practicals\Biostatistics I\Introduction to R\02_Common_Objects.html)

- [Indexing Subsetting](Practicals\Biostatistics I\Introduction to R\03_Indexing_Subsetting.html)

- [Data Transformation Exploration Visualization](Practicals\Biostatistics I\Introduction to R\04_Data_Transformation_Exploration_Visualization.html)

- [Distribution Functions](Practicals\Biostatistics I\Introduction to R\05_Distribution_Functions.html)

- [The Apply Family](Practicals\Biostatistics II\Introduction to R\The_Apply_Family.html)

- [Extra Programming Examples](Practicals\Biostatistics II\Introduction to R\Extra_Programming_Examples.html)


</div>


\


<div style="border:1px; border-style:solid; padding: 1em; border-color: #ffffff;
background: rgba(109, 121, 172, 0.4); color:black ">

# Statistical tests

An overview of the statistical tests can be found here: 
[Statistical tests](Outline_Notes.html) 

 
 
## Continuous data
 
### _Slides_

- [One Sample Tests](Slides\Biostatistics I\One_Sample_Tests.pdf)

- [Two Sample Independent Tests](Slides\Biostatistics I\Two_Sample_Ind_Tests.pdf)

- [Two Sample Dependent Tests](Slides\Biostatistics I\Two_Sample_Dep_Tests.pdf)

- [M Sample Tests](Slides\Biostatistics I\M_Sample_Tests.pdf)

- [Correlation Tests](Slides\Biostatistics I\Correlation_Tests.pdf)


### _Demos_

#### _Code_

- [Statistical Tests Continuous Data](Demos\Biostatistics I\Statistical_Tests_Continuous_Data.R)


#### _Output_

- [Statistical Tests Continuous Data](Demos\Biostatistics I\Statistical_Tests_Continuous_Data.html)


### _Practicals_

- [Statistical Tests Continuous Data](Practicals\Biostatistics I\Statistical tests\Statistical_Tests_Continuous_Data.html)


## Categorical data
 
### _Slides_ 

- [Proportion Tests](Slides\Biostatistics I\Proportion_Tests.pdf)

- [ChiSquare FisherExact Tests](Slides\Biostatistics I\ChiSquare_FisherExact_Tests.pdf)

- [McNemar Test](Slides\Biostatistics II\McNemar_Test.pdf)

### _Demos_

#### _Code_

- [Statistical Tests Categorical Data partI](Demos\Biostatistics I\Statistical_Tests_Categorical_Data_partI.R)


- [Statistical Tests Categorical Data partII](Demos\Biostatistics II\Statistical_Tests_Categorical_Data_partII.R)

#### Output

- [Statistical Tests Categorical Data partI](Demos\Biostatistics I\Statistical_Tests_Categorical_Data_partI.html)


- [Statistical Tests Categorical Data partII](Demos\Biostatistics II\Statistical_Tests_Categorical_Data_partII.html)


### _Practicals_

- [Statistical Tests Categorical Data partI](Practicals\Biostatistics I\Statistical tests\Statistical_Tests_Categorical_Data_partI.html)


- [Statistical Tests Categorical Data partII](Practicals\Biostatistics II\Statistical tests\Statistical_Tests_Categorical_Data_partII.html)

</div>